apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  targetNamespace: kube-system
  version: 1.15.6